# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cdc6e8ddd12fa35d28390219b89a30bcc044fc4852d29384f7ce2c62803a67fddebf1427848201958574d77f9971e75b760adcb4610b02da651620fa5ab2538

test:
  secret_key_base: 28fcdcb8df4ef2c5bee70045eccf5231d52e65091d7c3d3ddea8859a2fa68dc39be5cd9d135b61a6d0b3c4d6345f607fa2a7396bf024f5185adf76aa1f81891b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <%= binding.pry%>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_KEY_BASE"] %>
